### ISSUE TITLE
spack-bot vs spackbot

### ISSUE THREAD

**Issue by adamjstewart** [spack/spackbot#43]
The bot that comments on PRs is named `@spack-bot`, but the command to run it is named `@spackbot`. This is already leading to confusion: https://github.com/spack/spack/pull/25219#issuecomment-892133666

Can they have the same name? Or can the bot respond to both `@spack-bot` and `@spackbot`?

**Comment by haampie** [comment]
Would be nice if it autocompleted better, you have to enter `@spackb` before `@spackbot` is suggested

**Comment by adamjstewart** [comment]
I don't think there's much we can do about auto-completion other than to change the name so that it doesn't start with `spack`.

**Comment by haampie** [comment]
@backspot

**Comment by vsoch** [comment]
I had the bot responding to a hard coded list before but @tgamblin didn't like that and we changed to https://github.com/spack/spack-bot/blob/313c37e289be583175133597b458c9748997046e/spackbot/helpers.py#L32. So if y'all want to decide on a method that you like (hard coding again, or perhaps just changing the username to spackbot because we don't need the dash, or making the bot's name spack-bot, or removing hyphens before checking, that works for me).

**Comment by vsoch** [comment]
Personally I like "spackbot" because hyphens are yucky.

**Comment by vsoch** [comment]
Personally I’d just rename the app and call it a day.

**Comment by adamjstewart** [comment]
I'm fine with that solution.

**Comment by tgamblin** [comment]
I think we should rename the app and the repo - sound good?  I can do it

**Comment by tldahlgren** [comment]
> I think we should rename the app and the repo - sound good? I can do it

The consistency will be nice 6+ months down the line. 😁

**Comment by tgamblin** [comment]
ok repo is renamed...

**Comment by tgamblin** [comment]
Ok now I remember why there is a discrepancy.  Apps are in the same namespace as user accounts, and apps cannot be `@`'d.  What that means is you cannot just have an app called `spackbot` if you want to `@` the thing -- you have to have a user called `spackbot` to `@`.  And you cannot have both an app and a user called `spackbot`.

I renamed the app to `spackbot-app`.  I dunno what else we can really do -- if there is another name people like then lemme know.

**Comment by tgamblin** [comment]
Closing this until someone comes up with a decent suggestion.
